# Generated by Django 5.2.11 on 2026-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaGTIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=14)),
                ('ncm', models.CharField(max_length=8)),
                ('descricao', models.TextField()),
                ('retorno_sefaz', models.TextField(blank=True)),
                ('consultado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta GTIN',
                'verbose_name_plural': 'Consultas GTIN',
            },
        ),
    ]
