# Generated by Django 5.2.11 on 2026-02-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro0000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fiscal', 'SPED Fiscal'), ('registro', 'SPED Contribuições')], max_length=20)),
                ('periodo', models.DateField()),
                ('arquivo_original', models.FileField(upload_to='sped/')),
                ('processado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Registro 0000',
                'verbose_name_plural': 'Registros 0000',
                'unique_together': {('empresa', 'tipo', 'periodo')},
            },
        ),
    ]
