# Generated by Django 5.2.11 on 2026-02-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sped', '0003_registro0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroC110',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_inf', models.CharField(blank=True, max_length=6, verbose_name='Código da Informação')),
                ('txt_compl', models.TextField(blank=True, verbose_name='Texto Complementar')),
                ('registro_c100', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementares_c110', to='sped.registroc100')),
            ],
            options={
                'verbose_name': 'Informação Complementar C110',
                'verbose_name_plural': 'Informações Complementares C110',
            },
        ),
        migrations.CreateModel(
            name='RegistroC113',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_oper', models.CharField(blank=True, max_length=1, verbose_name='Indicador de Operação')),
                ('ind_emit', models.CharField(blank=True, max_length=1, verbose_name='Indicador do Emitente')),
                ('cod_part', models.CharField(blank=True, max_length=60, verbose_name='Código do Participante')),
                ('cod_mod', models.CharField(blank=True, max_length=2, verbose_name='Código do Modelo')),
                ('ser', models.CharField(blank=True, max_length=3, verbose_name='Série')),
                ('sub', models.CharField(blank=True, max_length=3, verbose_name='Subsérie')),
                ('num_doc', models.CharField(blank=True, max_length=9, verbose_name='Número do Documento')),
                ('dt_doc', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('chv_nfe', models.CharField(blank=True, max_length=44, verbose_name='Chave NF-e Referenciada')),
                ('registro_c100', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_c113', to='sped.registroc100')),
            ],
            options={
                'verbose_name': 'Documento Referenciado C113',
                'verbose_name_plural': 'Documentos Referenciados C113',
            },
        ),
    ]
