# Generated by Django 5.2.11 on 2026-02-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteManualICMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicial', models.CharField(max_length=7, verbose_name='Período Inicial')),
                ('periodo_final', models.CharField(max_length=7, verbose_name='Período Final')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de Ajuste')),
                ('descricao', models.CharField(max_length=200, verbose_name='Tipo de Ajuste')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Ajuste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_manuais_icms', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Ajuste Manual ICMS',
                'verbose_name_plural': 'Ajustes Manuais ICMS',
                'ordering': ['codigo'],
            },
        ),
    ]
