# Generated by Django 5.2.11 on 2026-02-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_ajustemanualicms'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEntradaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicial', models.CharField(max_length=7, verbose_name='Período Inicial')),
                ('periodo_final', models.CharField(max_length=7, verbose_name='Período Final')),
                ('chave_nfe', models.CharField(max_length=44, verbose_name='Chave NF-e')),
                ('codigo', models.CharField(max_length=60, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=4, verbose_name='CFOP')),
                ('unidade', models.CharField(blank=True, max_length=6, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('icms_cst', models.CharField(blank=True, max_length=3, verbose_name='CST ICMS')),
                ('icms_aliq', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Alíquota ICMS')),
                ('icms_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ICMS')),
                ('icms_st_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ICMS ST')),
                ('ipi_cst', models.CharField(blank=True, max_length=2, verbose_name='CST IPI')),
                ('ipi_aliq', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Alíquota IPI')),
                ('ipi_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IPI')),
                ('pis_cst', models.CharField(blank=True, max_length=2, verbose_name='CST PIS')),
                ('pis_aliq', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Alíquota PIS')),
                ('pis_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor PIS')),
                ('cofins_cst', models.CharField(blank=True, max_length=2, verbose_name='CST COFINS')),
                ('cofins_aliq', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Alíquota COFINS')),
                ('cofins_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor COFINS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_entrada_api', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Produto Entrada API',
                'verbose_name_plural': 'Produtos Entrada API',
                'indexes': [models.Index(fields=['empresa', 'periodo_inicial', 'periodo_final'], name='dashboards__empresa_e5093f_idx'), models.Index(fields=['chave_nfe'], name='dashboards__chave_n_5042db_idx')],
            },
        ),
    ]
