# Generated by Django 5.2.11 on 2026-02-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('regime_tributario', models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso'), ('3', 'Regime Normal')], max_length=1)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='IE')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('certificado_digital', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('senha_certificado', models.CharField(blank=True, max_length=100)),
                ('data_validade_certificado', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnae_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.cnae')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.uf', verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
